### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Strannik74** [mxrch/GHunt#105]
Hello Friend!
I have Windows 7
Here's a mistake
![321](https://user-images.githubusercontent.com/31668854/96170577-34e86800-0f3d-11eb-9dee-6bf1fdc40d95.jpg)

**Comment by NikolozCh** [comment]
Hey.

Can you provide more details please?
1) Have you tried running `check_and_gen.py`?
2) Is your internet connection stable?
3) Do you have any running proxies?

Your problem should be caused by internet connection, I assume. Thanks for mentioning by the way. I will add `try-exception` for it and pull the request

**Comment by mxrch** [comment]
Closing this issue since the author is not responding since 8 days.
