### ISSUE TITLE
IndexError: list index out of range error while Loading Map Data

### ISSUE THREAD

**Issue by greatkourosh** [mxrch/GHunt#184]
On Windows 10 Pro x64 20H2 (19042.685)

PS C:\WINDOWS\system32> docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt hunt.py  [something correct]@gmail.com

     .d8888b.  888    888                   888
    d88P  Y88b 888    888                   888
    888    888 888    888                   888
    888        8888888888 888  888 88888b.  888888
    888  88888 888    888 888  888 888 "88b 888
    888    888 888    888 888  888 888  888 888
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.
     "Y8888P88 888    888  "Y88888 888  888  "Y888

[+] Docker detected, profile pictures will not be saved.
[+] 1 account found !

------------------------------

[-] Couldn't find name

[-] Default profile picture

Last profile edit : 2020/12/03 06:59:00 (UTC)

Email : [something correct]@gmail.com
Google ID : [some integers]

Hangouts Bot : No

[+] Activated Google services :
- Maps

Google Maps : https://www.google.com/maps/contrib/[some integers]/reviews
Traceback (most recent call last):
  File "hunt.py", line 155, in <module>
    reviews = gmaps.scrape(gaiaID, client, cookies, config, config.headers, config.regexs["review_loc_by_id"], config.headless)
  File "/usr/src/app/lib/gmaps.py", line 49, in scrape
    data = source.split(';window.APP_INITIALIZATION_STATE=')[1].split(';window.APP_FLAGS')[0].replace("\\", "")
IndexError: list index out of range

**Comment by Zer0C00lness** [comment]
![image](https://user-images.githubusercontent.com/74936200/103456614-c1e1c880-4cc5-11eb-99b1-512ce0b4c6d4.jpeg)

**Comment by Zer0C00lness** [comment]
You'll need to find a couple apps specific for this use

**Comment by lightghost-stack** [comment]
😁

**Comment by Zer0C00lness** [comment]
I'm trying to figure usage of all the great things we do using. A single button iPhone

**Comment by Zer0C00lness** [comment]
As you should  as you should

**Comment by Zer0C00lness** [comment]
You're using a computer I have a phone bro that's what I'm trying to figure hear how everything you can click click click click click onto this one fucking button bro￼

**Comment by Zer0C00lness** [comment]
Man n then half you dudes just wanna be funny

**Comment by Zer0C00lness** [comment]
- [ ] Fuck I forgot![Uploading 103457140...]

**Comment by Zer0C00lness** [comment]
Index out of range: index error

**Comment by mxrch** [comment]
@greatkourosh can I have the target email you're trying with ? Here or in private (see my bio readme) ?
It will help with the debug.
Otherwise, you can add a `print(source)` just before the line `data = source.split(';window.APP_INITIALIZATION_STATE=')[1].split(';window.APP_FLAGS')[0].replace("\", "")` and put it on pastebin

**Comment by dannyazure** [comment]
Needmore11.11angels@icloud.comOn Jan 2, 2021 9:07 PM, mxrch <notifications@github.com> wrote:
@greatkourosh can I have the target email you're trying with ? Here or in private (see my bio readme) ?
It will help with the debug.
Otherwise, you can add a print(source) just before the line data = source.split(';window.APP_INITIALIZATION_STATE=')[1].split(';window.APP_FLAGS')[0].replace("\", "") in lib/gmaps.py and put it on pastebin

**Comment by greatkourosh** [comment]
> @greatkourosh can I have the target email you're trying with ? Here or in private (see my bio readme) ?
> It will help with the debug.
> Otherwise, you can add a `print(source)` just before the line `data = source.split(';window.APP_INITIALIZATION_STATE=')[1].split(';window.APP_FLAGS')[0].replace("\", "")` in lib/gmaps.py and put it on pastebin

I tried on khezmaster@gmail.com

**Comment by mxrch** [comment]
![image](https://user-images.githubusercontent.com/17338428/103493834-f2e00b80-4e33-11eb-83e2-03531fdfd04d.png)

@greatkourosh it's working pretty well for me, so I don't know why do you have this.
If the issue persist, please produce a debug output and put it on a pastebin.
Otherwise, let me know here so I can close this issue.

**Comment by greatkourosh** [comment]
> ![image](https://user-images.githubusercontent.com/17338428/103493834-f2e00b80-4e33-11eb-83e2-03531fdfd04d.png)
> 
> @greatkourosh it's working pretty well for me, so I don't know why do you have this.
> If the issue persist, please produce a debug output and put it on a pastebin.
> Otherwise, let me know here so I can close this issue.

It works pretty well this time. I don't know how. :D
