### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fortyxseven** [mxrch/GHunt#188]
so when i write the command python hunt.py -----@gmail.com this error appear

> python hunt.py xxxxx@gmail.com                                              1 ⨯
  File "hunt.py", line 58
    print(f"[+] {len(data['matches'])} account found !")
                                                                              ^
SyntaxError: invalid syntax

HOW CAN I FIX THIS CODE ?

**Comment by BahaaIbrahim3024** [comment]
I think you have an old version of python. try upgrading to the latest version of python. F-string literals have been added to python since python 3.6. 
or use ".format({len(data['matches'])}) " instead of "f" .
this answer is from : https://stackoverflow.com/questions/50401632/f-strings-giving-syntaxerror

**Comment by mxrch** [comment]
Thanks for answering @BahaaIbrahim3024.
@fortyxseven first hello, no need to scream in the issues, and you can try to be polite too. 🙃 
Indeed, you seems to be using Python 2, while the README specify the need of Python 3.7+.

**Comment by fortyxseven** [comment]
Thanks for the help, and @mxrch I didn’t scream, I was just trying to get attention x') . HAVE A NICE DAY !
