### ISSUE TITLE
Httpx Error on Debian10

### ISSUE THREAD

**Issue by Sajjad-s** [mxrch/GHunt#22]
after running this ` pip install httpx` on Debian 10 (Buster) this error shown : 
`Collecting httpx[http2]
  Could not find a version that satisfies the requirement httpx[http2] (from versions: )
No matching distribution found for httpx[http2]
`

**Comment by Droid-** [comment]
Also seeing this. Debian GNU/Linux 10

**Comment by ntallman** [comment]
Try using python3 everywhere the documentation says python. `python3 -m pip install -r requirements.txt`, `python3 .\check_and_gen.py`,  `python3 hunt.py myemail@gmail.com`.

**Comment by mxrch** [comment]
Thank you @ntallman.
I don't know why this happens because I already installed `httpx` many times on my Parrot VM with Debian 10 without issues, so just follow what @ntallman says and you'll should be good.
I'm closing this issue since this is not related to GHunt but (surely) a misconfiguration during your installation, but feel free to reopening it if someone has this issue even when following what's ntallman is saying, and even better if you come with a solution !

**Comment by Sajjad-s** [comment]
@ntallman Thank you the error got fixed.

**Comment by Sajjad-s** [comment]
> Try using python3 everywhere the documentation says python. `python3 -m pip install -r requirements.txt`, `python3 .\check_and_gen.py`, `python3 hunt.py myemail@gmail.com`.

@ntallman Thank you the error got fixed.
