### ISSUE TITLE
ImportError: cannot import name 'FirefoxOptions' from 'selenium.webdriver'

### ISSUE THREAD

**Issue by psyb1** [mxrch/GHunt#275]
When I try to run check_and_gen.py I get this error...

File "check_and_gen.py", line 10, in <module> from seleniumwire import webdriver File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver.py", line 4, in <module> from selenium.webdriver import FirefoxOptions  # noqa
ImportError: cannot import name 'FirefoxOptions' from 'selenium.webdriver' (/usr/local/lib/python3.8/dist-packges/selenium/webdriver/_init_.py)

**Comment by influenceralgorithms** [comment]
Hi @psyb1, I came across the same issue for a different repository. Turned out that I had the incorrect version of Selenium installed. I had version 3.4 installed, which actually has 'FirefoxProfile' as name for 'FirefoxOptions'. I updated my Selenium to the latest available, 4.1.0, and everything was fixed. So, this issue has to do with the version of your packages. Hopes this helps :)

**Comment by mxrch** [comment]
From now, these problems won't happen anymore since the introduction of the modwall in GHunt which will force users to update the libraries when specified in the requirements.txt !
