### ISSUE TITLE
Please add save to html/pdf

### ISSUE THREAD

**Issue by olalavui** [mxrch/GHunt#420]
Please add save to html/pdf report

**Comment by mxrch** [comment]
Hi ! No

**Comment by olalavui** [comment]
why not?

**Comment by micduffy** [comment]
I suspect because this opens up endless requirements around formatting, document libraries usage, maintenance etc. Plus, if it is important, then according to open source principles, people are encouraged to contribute new features in the form of pull requests.

People effectively volunteer their time to maintain these projects
