### ISSUE TITLE
Sapisidhash & Clients6 endpoints

### ISSUE THREAD

**Issue by llvmx** [mxrch/GHunt#453]
I see there are some API calls for which the sapisidhash is being used. If I am not mistaken, you can bypass quota limits and other restrictions by using this type of auth method.
Now I would like to know if some other API endpoints, which are hosted on clients6 or on googleapis don't work with sapisidhash, because they return INVALID_ARGUMENT with no hint as to why this error appears (even those with no parameters).
I have used official API keys to generate the hash in the same way as in this project. It works with oauth, but not with sapisid.
Perhaps someone does have resources on this matter? Maybe I am missing certain cookies for the request.

@mxrch 
Since you worked on this and used it for the Calendar and People requests, I would appreciate it if you could share your knowledge.

**Comment by llvmx** [comment]
Thanks for the response.
Guess it's true there are still limits since google is limiting per user on their internal projects.
However, I was confused why Sapisidhash is used for the calendar/people API, because oauth would have worked out as well I think.

**Comment by mxrch** [comment]
Because oauth2 is more relevant in mobile apps.
You first register a device (your phone), then generate a master token and keep on the device.
And with this master token you generate oauth2 tokens for all the apps you want.

The SAPISIDHASH is more appropriate for a browser because it's only a variation of the SAPISID cookie, and these cookies are variable inside the *.google.com scope, so you don't have to do the oauth2 flow for each Google service you're navigating to.
